### ISSUE TITLE
Openplotter-serial creates invalid udev statements for USB by Position

### ISSUE THREAD

**Issue by jongough** [openplotter/openplotter-serial#5]
When adding new USB devices using the GUI the UDEV file contains invalid definitions for devices. After reboot the devices are not found correctly due to the random nature in which USB devices are allocated at startup. The UDEV file contains:
```
KERNEL=="ttyUSB1*", KERNELS=="1-1.5.4:1.0",SYMLINK+="ttyOP_gps4"
KERNEL=="ttyUSB2*", KERNELS=="1-1.5.2:1.0",SYMLINK+="ttyOP_autop"
KERNEL=="ttyUSB3*", KERNELS=="1-1.5.1:1.0",SYMLINK+="ttyOP_wind"
```
but should contain:
```
KERNEL=="ttyUSB*", KERNELS=="1-1.5.4:1.0",SYMLINK+="ttyOP_gps4"
KERNEL=="ttyUSB*", KERNELS=="1-1.5.2:1.0",SYMLINK+="ttyOP_autop"
KERNEL=="ttyUSB*", KERNELS=="1-1.5.1:1.0",SYMLINK+="ttyOP_wind"
```
as this allows for the random suffix number.

**Comment by sailoog** [comment]
thanks a lot I have merged it and I will publish a new version ASAP

**Comment by jongough** [comment]
Any idea when you may publish? I am going cruising and would like to update to the new version before I go in a couple of weeks. Thanks

**Comment by sailoog** [comment]
I will try this weekend ;)

**Comment by jongough** [comment]
Thanks!

**Comment by sailoog** [comment]
done

**Comment by jongough** [comment]
The version number has not changed and therefore this fix is not listed as available to install/upgrade. The version is still showing as 2.2.1-stable, perhaps this should be 2.2.2-stable?

**Comment by sailoog** [comment]
click on "update candidates" to update the list

**Comment by jongough** [comment]
Thanks. I had done that a couple of times and it did not show up. I think it may have been the date on the system had not been updated as there is currently no GPS connected. Set the date manually, rebooted and was then able to install 2.2.3.
